apiVersion: v1
kind: Service
metadata:
  name: novnc
  namespace: robot-demo
  labels:
    app: gazebo-sim
    app.kubernetes.io/name: robot-demo
spec:
  selector:
    app: gazebo-sim
  ports:
    - name: novnc
      port: 6080
      targetPort: 6080
      protocol: TCP
  type: ClusterIP
